### ISSUE TITLE
installation hogs huge amount of RAM (24GB)

### ISSUE THREAD

**Issue by yarikoptic** [pyhrf/pyhrf#139]
Tried to install pyhrf (current master with my PR #138 ) in virtualenv.  Poor laptop hogged and I saw that the python process consumed already 24GB -- had to kill it to restore sanity. Last lines are below... what was it doing and how much RAM do I need to install the beast?

```
Running matplotlib-1.3.1/setup.py -q bdist_egg --dist-dir /home/yoh/.tmp/easy_install-9zkQIp/matplotlib-1.3.1/egg-dist-tmp-X8i0lF
============================================================================
Edit setup.cfg to change the build options

BUILDING MATPLOTLIB
            matplotlib: yes [1.3.1]
                python: yes [2.7.10+ (default, Oct 10 2015, 09:11:24)  [GCC
                        5.2.1 20151028]]
              platform: yes [linux2]

REQUIRED DEPENDENCIES AND EXTENSIONS
                 numpy: yes [version 1.9.2]
              dateutil: yes [using dateutil version 2.2]
               tornado: yes [using tornado version 4.2.1]
             pyparsing: yes [using pyparsing version 2.0.3]
                 pycxx: yes [Couldn't import.  Using local copy.]
                libagg: yes [pkg-config information for 'libagg' could not
                        be found. Using local copy.]
              freetype: yes [version 18.0.12]
                   png: yes [version 1.2.50]

OPTIONAL SUBPACKAGES
           sample_data: yes [installing]
              toolkits: yes [installing]
                 tests: yes [using nose version 1.3.6]

OPTIONAL BACKEND EXTENSIONS
                macosx: no  [Mac OS-X only]
                qt4agg: yes [installing, Qt: 4.8.7, PyQt4: 4.11.4]
               gtk3agg: yes [installing, version 3.2.18]
             gtk3cairo: yes [installing, version 3.2.18]
                gtkagg: no  [The C/C++ header for pygtk (pygtk/pygtk.h)
                        could not be found.  You may need to install the
                        development package.]
                 tkagg: yes [installing, version 81008]
                 wxagg: yes [installing, version 3.0.2.0]
                   gtk: no  [The C/C++ header for pygtk (pygtk/pygtk.h)
                        could not be found.  You may need to install the
                        development package.]
                   agg: yes [installing]
                 cairo: yes [installing, version 1.8.8]
             windowing: no  [Microsoft Windows only]

OPTIONAL LATEX DEPENDENCIES
                dvipng: yes [version 1.14]
           ghostscript: yes [version 9.16]
                 latex: yes [version 3.14159265]
               pdftops: yes [version 0.26.5]

[1]    28163 terminated  python setup.py install --verbose
```

**Comment by thperret** [comment]
Sorry for not having answered earlier, I just saw the mail notifications today (?).
Could you tell me the distribution you're using?
I have myself, installed pyhrf in several virtual environment and never faced this error. The problem could be that when you're using a virtualenv, by default it does not uses the system packages and must build all libraries for pyhrf dependancies. The logs you provides show the building of matplotlib libraries which could lead to that problem (only a wild guess). Another problem could be the version of matplotlib. For now, there is a bug in pyhrf with matplotlib versions >1.4 and you must install the 1.3.1 one.
You could try to install them step by step:
```bash
$ source path/to/environment/activate
(pyhrf-venv) $ pip install numpy
(pyhrf-venv) $ pip install scipy
(pyhrf-venv) $ pip install "matplotlib<1.4"
(pyhrf-venv) $ pip install nibabel
(pyhrf-venv) $ pip install sympy
(pyhrf-venv) $ pip install nipy
```
optional dependencies:
```bash
(pyhrf-venv) $ pip install joblib
(pyhrf-venv) $ pip install scikit-learn
(pyhrf-venv) $ pip install sphinx (only for building documentation)
(pyhrf-venv) $ pip install pygraphviz
(pyhrf-venv) $ pip install Pillow
```
then install pyhrf iteself, either with the lastest release available on pypi:
```bash
(pyhrf-venv) $ pip install pyhrf
```
or installing the lastest version on github:
```bash
(pyhrf-venv) $ pip install [-e] git+https://github.com/pyhrf/pyhrf#egg=pyhrf
```
or your local version:
```bash
(pyhrf-venv) $ pip install [-e] .
```
the `-e` flag install in develop mode (same as running python setup.py develop)

**Comment by yarikoptic** [comment]
installing numpy/scipy via plain pip is always a recipe of trouble. with wheels situation improved for e.g. windows, but not really for linux.

nevertheless -- I have tried in a clean virtualenv , but then installation of scipy fails with
```

  File "/home/yoh/deb/perspect/pyhrf/venv-manual/local/lib/python2.7/site-packages/numpy/distutils/npy_pkg_config.py", line 299, in _read_config

    meta, vars, sections, reqs = parse_config(f, dirs)

  File "/home/yoh/deb/perspect/pyhrf/venv-manual/local/lib/python2.7/site-packages/numpy/distutils/npy_pkg_config.py", line 271, in parse_config

    raise PkgNotFound("Could not find file(s) %s" % str(filenames))

numpy.distutils.npy_pkg_config.PkgNotFound: Could not find file(s) ['/home/yoh/deb/perspect/pyhrf/venv-manual/local/lib/python2.7/site-packages/numpy/core/lib/npy-pkg-config/npymath.ini']

----------------------------------------
Cleaning up...
Command /home/yoh/deb/perspect/pyhrf/venv-manual/bin/python2 -c "import setuptools, tokenize;__file__='/home/yoh/.tmp/pip-build-F2veaD/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /home/yoh/.tmp/pip-VoPasq-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/yoh/deb/perspect/pyhrf/venv-manual/include/site/python2.7 failed with error code 1 in /home/yoh/.tmp/pip-build-F2veaD/scipy
Traceback (most recent call last):
  File "/home/yoh/deb/perspect/pyhrf/venv-manual/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/yoh/deb/perspect/pyhrf/venv-manual/local/lib/python2.7/site-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/home/yoh/deb/perspect/pyhrf/venv-manual/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 51: ordinal not in range(128)
```

if I let virtualenv use system wide versions and start by installing lower versioned matplotlib only -- then that one fails with

```

c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/ft2font.o build/temp.linux-x86_64-2.7/src/mplutils.o build/temp.linux-x86_64-2.7/usr/src/CXX/cxxsupport.o build/temp.linux-x86_64-2.7/usr/src/CXX/cxx_extensions.o build/temp.linux-x86_64-2.7/usr/src/CXX/IndirectPythonInterface.o build/temp.linux-x86_64-2.7/usr/src/CXX/cxxextensions.o -L/usr/local/lib -lfreetype -lstdc++ -lm -o build/lib.linux-x86_64-2.7/matplotlib/ft2font.so

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crti.o: unrecognized relocation (0x2a) in section `.init'

/usr/bin/ld: final link failed: Bad value

collect2: error: ld returned 1 exit status

error: command 'c++' failed with exit status 1

----------------------------------------
  Can't roll back matplotlib; was not uninstalled
Cleaning up...
Command /home/yoh/deb/perspect/pyhrf/venv-system-manual-mpl/bin/python -c "import setuptools, tokenize;__file__='/home/yoh/.tmp/pip-build-Z_25oC/matplotlib/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /home/yoh/.tmp/pip-iyJaYp-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/yoh/deb/perspect/pyhrf/venv-system-manual-mpl/include/site/
```

how severe is incompatibility with mpl, may be pyhrf could become compatible again with recent matplotlib? ;)

**Comment by thperret** [comment]
Concerning the scipy error when installing with pip, check that all build dependencies are installed. On Debian-like systems, you can run (as root) `apt-get build-dep python-numpy python-scipy` ; on Fedora-like systems, you can run (as root) `yum-builddep numpy scipy` or on newer systems (Fedora>22) `dnf builddep numpy scipy`. For other unsupported systems, please report to your system documentation.
There's great chances that you'll also need to run the same commands for matplotlib build dependencies.

Concerning the matplotlib incompatibility, I didn't checked since a long time the latests versions with pyhrf because we officially support only Ubuntu 12.04/14.04 and Fedora 20/21 which all provide matplotlib version <1.4. I didn't recall what was the problem exactly but I pretty sure that is easily fixable. I'll checked that in the following days.

**Comment by yarikoptic** [comment]
indeed I was missing some but even after installing all of them -- "no go" e.g. for matplotlib on my debian testing/unstable, which wouldn't be surprising since many of those dependencies might grow incompatible with older versions of it.  As for the versions of mpl:

```
$> whohas -D Debian,Ubuntu --strict python-matplotlib
Ubuntu  python-matplotlib   1.1.1~rc1+git20120  http://packages.ubuntu.com/precise/python-matplotlib
Ubuntu  python-matplotlib   1.3.1-1ubuntu5      http://packages.ubuntu.com/trusty/python-matplotlib
Ubuntu  python-matplotlib   1.4.2-3.1           http://packages.ubuntu.com/vivid/python-matplotlib
Ubuntu  python-matplotlib   1.4.2-3.1ubuntu1    http://packages.ubuntu.com/wily/python-matplotlib
Ubuntu  python-matplotlib   1.5.1~rc1-1ubuntu1  http://packages.ubuntu.com/xenial/python-matplotlib
Debian  python-matplotlib   0.99.3-1            http://packages.debian.org/squeeze/python-matplotlib
Debian  python-matplotlib   1.1.0-1~bpo60+1     http://packages.debian.org/squeeze-backports/python-matplotlib
Debian  python-matplotlib   1.1.1~rc2-1         http://packages.debian.org/wheezy/python-matplotlib
Debian  python-matplotlib   1.4.2-3.1           http://packages.debian.org/jessie/python-matplotlib
Debian  python-matplotlib   1.5.1~rc1-1         http://packages.debian.org/stretch/python-matplotlib
Debian  python-matplotlib   1.5.1~rc1-1         http://packages.debian.org/sid/python-matplotlib

```
so all recent releases moved on beyond < 1.4.  Without having it compatible with recent mpl I can't even approach packaging pyhrf for (Neuro)Debian ;)

**Comment by thperret** [comment]
After running some tests, it seems like the problem comes from an incompatibility with the latests version of numpy and the old version of matplotlib supported by pyhrf. The "easiest" way to install pyhrf in virtual environment is to use the versions that are officially supported by pyhrf (so the versions of ubuntu 14.04 LTS). If you want to try again, you can run(inside your virtualenv):
```bash
(pyhrf-venv) $ pip install numpy==1.8.2
(pyhrf-venv) $ pip install scipy==0.13.3
(pyhrf-venv) $ pip install matplotlib==1.3.1
(pyhrf-venv) $ pip install sympy==0.7.4.1
(pyhrf-venv) $ pip install nibabel==1.2.2
(pyhrf-venv) $ pip install nipy==0.3.0
(pyhrf-venv) $ pip install joblib==0.7.1
(pyhrf-venv) $ pip install scikit-learn==0.14.1
(pyhrf-venv) $ pip install python-graph-core==1.8.2
(pyhrf-venv) $ pip install munkres==1.0.6
(pyhrf-venv) $ pip install Pillow==2.3.0
```
Let me know if it works on your side.

I'll further investigate to support latest versions of all libraries but keep in mind that we're only supporting LTS version of Ubuntu. So before the next LTS is released (in april) the packages versions after 14.04 ones will not be officially supported.

Concerning the packaging of pyhrf for NeuroDebian (or any distribution), I think that the package is not stable enough for now. We plan to modify a large part of the structure of the code and I don't think it's wise to spend time on that while the package is not stable. I plan to start packaging it with the 0.5.0 release which will clean the code and bring a stable API for external use.

**Comment by yarikoptic** [comment]
Gy, i guess next time I edit some "software paper" I will demand first to get it in a state stable enough to be ready for "external use", since otherwise there is much lesser value of such publication ;-)  Meanwhile I guess I will try in a 14.04 chroot and will report on that later

**Comment by thperret** [comment]
In fact when the [pyhrf software paper](http://journal.frontiersin.org/article/10.3389/fnins.2014.00067/abstract) was released, [pyhrf (version 0.3)](https://github.com/pyhrf/pyhrf/releases/tag/0.3) was stable. At that time, the officially supported distributions was Ubuntu 12.04 (and maybe 14.04?) and was based on the MCMC approach for the JDE framework. Since then, we improved and implemented the VEM approach which is (a lot) faster than the MCMC one. Doing that allowed us to rework the package and that's why it's not considered stable for now.

I'll close this issue, please reopen it if you encounter this error again.

**Comment by philouc** [comment]
Dear Yaroslav,

I confirm what Thomas said earlier. Since mid 2014, we have been
refactoring the core of the Pyhrf code to make it more efficient (replacing
our previous MCMC implementation by a VEM one) and user-friendly. This is
big step forward that requires some manpower & time which may seem
incompatible with your requirements at the first glance. But be sure that
this will allow us quite soon to be appealing not only to cognitive
neuroscience but also for clinical applications too (Stroke, Alzheimer).
Our current end-user who are funding the project are not only colleagues in
the fMRI community but also hospitals. For this reason, we need faster
result delivery. This is what we deeply investigated over the last months.
We'll try to account for your comments ASAP, especially during our
forthcoming coding sprint in Feb.

Best,
Philippe


On Sun, Jan 24, 2016 at 12:30 PM, Thomas Perret <notifications@github.com>
wrote:

> In fact when the pyhrf software paper
> <http://journal.frontiersin.org/article/10.3389/fnins.2014.00067/abstract>
> was released, pyhrf (version 0.3)
> <https://github.com/pyhrf/pyhrf/releases/tag/0.3> was stable. At that
> time, the officially supported distributions was Ubuntu 12.04 (and maybe
> 14.04?) and was based on the MCMC approach for the JDE framework. Since
> then, we improved and implemented the VEM approach which is (a lot) faster
> than the MCMC one. Doing that allowed us to rework the package and that's
> why it's not considered stable for now.
>
> I'll close this issue, please reopen it if you encounter this error again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyhrf/pyhrf/issues/139#issuecomment-174285168>.
>



-- 
==========================
CIUCIU Philippe, PhD
CEA/NeuroSpin (INRIA Parietal team)

*Postal Address*:
CEA Saclay, Neurospin
Bât. 145, Point Courrier 156
91191 Gif-sur-Yvette cedex, France
Phone/Fax: 33 1 6908 7785/7980
http://team.inria.fr/parietal
http://sites.google.com/site/philippeciuciu/
==========================

**Comment by yarikoptic** [comment]
Great to hear that there are such exciting developments!
Given that this repository is not regularly updated, what would you recommend -- should I keep trying current master or some previous release?

**Comment by thperret** [comment]
Depending on your use of the software, I would recommend either to use the [stable version from pypi](https://pypi.python.org/pypi/pyhrf) or if you want to use bleeding edge improvements you can use the master branch of this repo.

**Comment by philouc** [comment]
Thanks Thomas to closing this issue and answering Yaroslav's question.

On Thu, Jan 28, 2016 at 2:47 PM, Thomas Perret <notifications@github.com>
wrote:

> Depending on your use of the software, I would recommend either to use the stable
> version from pypi <https://pypi.python.org/pypi/pyhrf> or if you want to
> use bleeding edge improvements you can use the master branch of this repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyhrf/pyhrf/issues/139#issuecomment-176192015>.
>



-- 
==========================
CIUCIU Philippe, PhD
CEA/NeuroSpin (INRIA Parietal team)

*Postal Address*:
CEA Saclay, Neurospin
Bât. 145, Point Courrier 156
91191 Gif-sur-Yvette cedex, France
Phone/Fax: 33 1 6908 7785/7980
http://team.inria.fr/parietal
http://sites.google.com/site/philippeciuciu/
==========================
